services:
  - type: web
    name: Tell-Me
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.enableCORS=false
    envVars:
      - key: GROQ_API_KEY
        value: your-groq-key-here
